### ISSUE TITLE
docker to run jupyter + cling

### ISSUE THREAD

**Issue by KHIEM2812** [RobInLabUJI/ROS-Tutorials#4]
There are some examples of c++ ros using on jupyter in this repo. however, from the repo, it doesnt show any relevant installations from dockerfile to run cling or any steps in notebook to include c++ ros libraries, headers. 

i also tried to pull the docker but seems that it doesnt have info that im looking for. the online binder can run python kernel only. anyone here know how to do that already?

**Comment by ecervera** [comment]
You should checkout the branch "cling" of the repository and build the docker image.

**Comment by KHIEM2812** [comment]
turned out my setup has some problem. After i reinstalled, it is working. thank you.
